---
version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run  here #optional
    volumes:
      - /srv/<your folder name here>/config/jackett:/config
      - /srv/<your folder name here>/Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - UMASK_SET=022 #optional
    volumes:
      - /srv/<your folder name here>/config/sonarr:/config
      - /srv/<your folder name here>/Series:/tv
      - /srv/<your folder name here>/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - UMASK_SET=022 #optional
    volumes:
      - /srv/<your folder name here>/config/radarr:/config
      - /srv/<your folder name here>/Movies:/movies
      - /srv/<your folder name here>/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=<claim code>
    volumes:
      - /srv/<your folder name here>/configs/plex:/config
      - /srv/<your folder name here>/Series:/tv
      - /srv/<your folder name here>/Movies:/movies
      - /srv/<your folder name here>/music:/music
      - /srv/<your folder name here>/audiobooks:/audiobooks
      - /srv/<your folder name here>/docker/plex/logs:/logs
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /srv/<your folder name here>/config/lazylibrarian:/config
      - /srv/<your folder name here>/Downloads:/downloads
      - /srv/<your folder name here>/Books:/books
      - /srv/<your folder name here>/audiobooks:/audiobooks
    ports:
      - 5299:5299
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin
      - PASS=<downloaderpassword>
    volumes:
      - /srv/<your folder name here>/configs/transmission:/config
      - /srv/<your folder name here>/Downloads:/downloads
      - /srv/<your folder name here>/Downloads:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

networks:
  default:
    external:
      name: mediacenter